spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC
    username: root
    password: naz180599
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
        hibernate.hbm2ddl.auto: update
server:
  port: 8081